package com.lizhivscaomei.jes.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysDomain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.id
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.code
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.name
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.index
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.useable
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String useable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.create_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.create_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.update_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.update_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.remarks
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_domain.del_flag
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_domain
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.id
     *
     * @return the value of sys_domain.id
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.id
     *
     * @param id the value for sys_domain.id
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.code
     *
     * @return the value of sys_domain.code
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.code
     *
     * @param code the value for sys_domain.code
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.name
     *
     * @return the value of sys_domain.name
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.name
     *
     * @param name the value for sys_domain.name
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.index
     *
     * @return the value of sys_domain.index
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.index
     *
     * @param index the value for sys_domain.index
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setIndex(String index) {
        this.index = index == null ? null : index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.useable
     *
     * @return the value of sys_domain.useable
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getUseable() {
        return useable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.useable
     *
     * @param useable the value for sys_domain.useable
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setUseable(String useable) {
        this.useable = useable == null ? null : useable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.create_by
     *
     * @return the value of sys_domain.create_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.create_by
     *
     * @param createBy the value for sys_domain.create_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.create_date
     *
     * @return the value of sys_domain.create_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.create_date
     *
     * @param createDate the value for sys_domain.create_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.update_by
     *
     * @return the value of sys_domain.update_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.update_by
     *
     * @param updateBy the value for sys_domain.update_by
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.update_date
     *
     * @return the value of sys_domain.update_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.update_date
     *
     * @param updateDate the value for sys_domain.update_date
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.remarks
     *
     * @return the value of sys_domain.remarks
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.remarks
     *
     * @param remarks the value for sys_domain.remarks
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_domain.del_flag
     *
     * @return the value of sys_domain.del_flag
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_domain.del_flag
     *
     * @param delFlag the value for sys_domain.del_flag
     *
     * @mbggenerated Wed Mar 28 21:06:17 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}