package com.lizhivscaomei.jes.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysDict implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.name
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.code
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.type
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.description
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.sort
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.parent_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.parent_ids
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.create_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.create_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.update_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.update_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.remarks
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.domain_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.name
     *
     * @return the value of sys_dict.name
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.name
     *
     * @param name the value for sys_dict.name
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.code
     *
     * @return the value of sys_dict.code
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.code
     *
     * @param code the value for sys_dict.code
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.type
     *
     * @return the value of sys_dict.type
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.type
     *
     * @param type the value for sys_dict.type
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.description
     *
     * @return the value of sys_dict.description
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.description
     *
     * @param description the value for sys_dict.description
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.sort
     *
     * @return the value of sys_dict.sort
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.sort
     *
     * @param sort the value for sys_dict.sort
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.parent_id
     *
     * @return the value of sys_dict.parent_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.parent_id
     *
     * @param parentId the value for sys_dict.parent_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.parent_ids
     *
     * @return the value of sys_dict.parent_ids
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.parent_ids
     *
     * @param parentIds the value for sys_dict.parent_ids
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_by
     *
     * @return the value of sys_dict.create_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_by
     *
     * @param createBy the value for sys_dict.create_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_date
     *
     * @return the value of sys_dict.create_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_date
     *
     * @param createDate the value for sys_dict.create_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.update_by
     *
     * @return the value of sys_dict.update_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.update_by
     *
     * @param updateBy the value for sys_dict.update_by
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.update_date
     *
     * @return the value of sys_dict.update_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.update_date
     *
     * @param updateDate the value for sys_dict.update_date
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.remarks
     *
     * @return the value of sys_dict.remarks
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.remarks
     *
     * @param remarks the value for sys_dict.remarks
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.domain_id
     *
     * @return the value of sys_dict.domain_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.domain_id
     *
     * @param domainId the value for sys_dict.domain_id
     *
     * @mbggenerated Sat May 19 16:16:15 CST 2018
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }
}