package com.lizhivscaomei.jes.sys.entity;

public class VSysUserRoleDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.user_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.role_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.user_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.role_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.domain_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_user_role_domain.domain_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    private String domainName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.user_id
     *
     * @return the value of v_sys_user_role_domain.user_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.user_id
     *
     * @param userId the value for v_sys_user_role_domain.user_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.role_id
     *
     * @return the value of v_sys_user_role_domain.role_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.role_id
     *
     * @param roleId the value for v_sys_user_role_domain.role_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.user_name
     *
     * @return the value of v_sys_user_role_domain.user_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.user_name
     *
     * @param userName the value for v_sys_user_role_domain.user_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.role_name
     *
     * @return the value of v_sys_user_role_domain.role_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.role_name
     *
     * @param roleName the value for v_sys_user_role_domain.role_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.domain_id
     *
     * @return the value of v_sys_user_role_domain.domain_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.domain_id
     *
     * @param domainId the value for v_sys_user_role_domain.domain_id
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_user_role_domain.domain_name
     *
     * @return the value of v_sys_user_role_domain.domain_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_user_role_domain.domain_name
     *
     * @param domainName the value for v_sys_user_role_domain.domain_name
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }
}