package com.lizhivscaomei.jes.sys.dao;

import com.lizhivscaomei.jes.sys.entity.SysDomain;
import com.lizhivscaomei.jes.sys.entity.SysDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @SelectProvider(type=SysDomainSqlProvider.class, method="countByExample")
    int countByExample(SysDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @DeleteProvider(type=SysDomainSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @Delete({
        "delete from sys_domain",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @Insert({
        "insert into sys_domain (id, name, ",
        "code, home_page, ",
        "useable, create_by, ",
        "create_date, update_by, ",
        "update_date, remarks)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{code,jdbcType=VARCHAR}, #{homePage,jdbcType=VARCHAR}, ",
        "#{useable,jdbcType=VARCHAR}, #{createBy,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{remarks,jdbcType=VARCHAR})"
    })
    int insert(SysDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @InsertProvider(type=SysDomainSqlProvider.class, method="insertSelective")
    int insertSelective(SysDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @SelectProvider(type=SysDomainSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="home_page", property="homePage", jdbcType=JdbcType.VARCHAR),
        @Result(column="useable", property="useable", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    List<SysDomain> selectByExample(SysDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @Select({
        "select",
        "id, name, code, home_page, useable, create_by, create_date, update_by, update_date, ",
        "remarks",
        "from sys_domain",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="home_page", property="homePage", jdbcType=JdbcType.VARCHAR),
        @Result(column="useable", property="useable", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    SysDomain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @UpdateProvider(type=SysDomainSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysDomain record, @Param("example") SysDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @UpdateProvider(type=SysDomainSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysDomain record, @Param("example") SysDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @UpdateProvider(type=SysDomainSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_domain
     *
     * @mbggenerated Sat Apr 28 14:39:31 CST 2018
     */
    @Update({
        "update sys_domain",
        "set name = #{name,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "home_page = #{homePage,jdbcType=VARCHAR},",
          "useable = #{useable,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "remarks = #{remarks,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysDomain record);
}