package com.lizhivscaomei.jes.sys.dao;

import com.lizhivscaomei.jes.sys.entity.SysMdict;
import com.lizhivscaomei.jes.sys.entity.SysMdictExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysMdictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @SelectProvider(type=SysMdictSqlProvider.class, method="countByExample")
    int countByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @DeleteProvider(type=SysMdictSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @Delete({
        "delete from sys_mdict",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @Insert({
        "insert into sys_mdict (id, parent_id, ",
        "parent_ids, name, ",
        "sort, description, ",
        "create_by, create_date, ",
        "update_by, update_date, ",
        "remarks, del_flag, domain_id)",
        "values (#{id,jdbcType=VARCHAR}, #{parentId,jdbcType=VARCHAR}, ",
        "#{parentIds,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=DECIMAL}, #{description,jdbcType=VARCHAR}, ",
        "#{createBy,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{remarks,jdbcType=VARCHAR}, #{delFlag,jdbcType=CHAR}, #{domainId,jdbcType=VARCHAR})"
    })
    int insert(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @InsertProvider(type=SysMdictSqlProvider.class, method="insertSelective")
    int insertSelective(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @SelectProvider(type=SysMdictSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_ids", property="parentIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.DECIMAL),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.CHAR),
        @Result(column="domain_id", property="domainId", jdbcType=JdbcType.VARCHAR)
    })
    List<SysMdict> selectByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @Select({
        "select",
        "id, parent_id, parent_ids, name, sort, description, create_by, create_date, ",
        "update_by, update_date, remarks, del_flag, domain_id",
        "from sys_mdict",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_ids", property="parentIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.DECIMAL),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.CHAR),
        @Result(column="domain_id", property="domainId", jdbcType=JdbcType.VARCHAR)
    })
    SysMdict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysMdict record, @Param("example") SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysMdict record, @Param("example") SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbggenerated Wed Mar 28 21:19:21 CST 2018
     */
    @Update({
        "update sys_mdict",
        "set parent_id = #{parentId,jdbcType=VARCHAR},",
          "parent_ids = #{parentIds,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=DECIMAL},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "remarks = #{remarks,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=CHAR},",
          "domain_id = #{domainId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysMdict record);
}