package com.lizhivscaomei.jes.sys.dao;

import com.lizhivscaomei.jes.sys.entity.VSysUserRoleDomain;
import com.lizhivscaomei.jes.sys.entity.VSysUserRoleDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface VSysUserRoleDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @SelectProvider(type=VSysUserRoleDomainSqlProvider.class, method="countByExample")
    int countByExample(VSysUserRoleDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @DeleteProvider(type=VSysUserRoleDomainSqlProvider.class, method="deleteByExample")
    int deleteByExample(VSysUserRoleDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @Insert({
        "insert into v_sys_user_role_domain (user_id, role_id, ",
        "user_name, role_name, ",
        "domain_id, domain_name)",
        "values (#{userId,jdbcType=VARCHAR}, #{roleId,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{roleName,jdbcType=VARCHAR}, ",
        "#{domainId,jdbcType=VARCHAR}, #{domainName,jdbcType=VARCHAR})"
    })
    int insert(VSysUserRoleDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @InsertProvider(type=VSysUserRoleDomainSqlProvider.class, method="insertSelective")
    int insertSelective(VSysUserRoleDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @SelectProvider(type=VSysUserRoleDomainSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain_id", property="domainId", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain_name", property="domainName", jdbcType=JdbcType.VARCHAR)
    })
    List<VSysUserRoleDomain> selectByExample(VSysUserRoleDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @UpdateProvider(type=VSysUserRoleDomainSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VSysUserRoleDomain record, @Param("example") VSysUserRoleDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @UpdateProvider(type=VSysUserRoleDomainSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VSysUserRoleDomain record, @Param("example") VSysUserRoleDomainExample example);
}