package com.lizhivscaomei.jes.sys.dao;

import com.lizhivscaomei.jes.sys.entity.VSysUserDomainMenu;
import com.lizhivscaomei.jes.sys.entity.VSysUserDomainMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface VSysUserDomainMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @SelectProvider(type=VSysUserDomainMenuSqlProvider.class, method="countByExample")
    int countByExample(VSysUserDomainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @DeleteProvider(type=VSysUserDomainMenuSqlProvider.class, method="deleteByExample")
    int deleteByExample(VSysUserDomainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @Insert({
        "insert into v_sys_user_domain_menu (user_id, id, ",
        "parent_id, parent_ids, ",
        "name, sort, href, ",
        "target, icon, is_show, ",
        "permission, create_by, ",
        "create_date, update_by, ",
        "update_date, remarks, ",
        "del_flag, domain_id)",
        "values (#{userId,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=VARCHAR}, #{parentIds,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{sort,jdbcType=DECIMAL}, #{href,jdbcType=VARCHAR}, ",
        "#{target,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR}, #{isShow,jdbcType=CHAR}, ",
        "#{permission,jdbcType=VARCHAR}, #{createBy,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{remarks,jdbcType=VARCHAR}, ",
        "#{delFlag,jdbcType=CHAR}, #{domainId,jdbcType=VARCHAR})"
    })
    int insert(VSysUserDomainMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @InsertProvider(type=VSysUserDomainMenuSqlProvider.class, method="insertSelective")
    int insertSelective(VSysUserDomainMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @SelectProvider(type=VSysUserDomainMenuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_ids", property="parentIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.DECIMAL),
        @Result(column="href", property="href", jdbcType=JdbcType.VARCHAR),
        @Result(column="target", property="target", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.CHAR),
        @Result(column="permission", property="permission", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.CHAR),
        @Result(column="domain_id", property="domainId", jdbcType=JdbcType.VARCHAR)
    })
    List<VSysUserDomainMenu> selectByExample(VSysUserDomainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @UpdateProvider(type=VSysUserDomainMenuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VSysUserDomainMenu record, @Param("example") VSysUserDomainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_domain_menu
     *
     * @mbggenerated Mon Jun 04 14:31:14 CST 2018
     */
    @UpdateProvider(type=VSysUserDomainMenuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VSysUserDomainMenu record, @Param("example") VSysUserDomainMenuExample example);
}