package com.lizhivscaomei.jes.sys.dao;

import com.lizhivscaomei.jes.sys.entity.VSysUserRoleDomain;
import com.lizhivscaomei.jes.sys.entity.VSysUserRoleDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

public interface VSysUserRoleDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Wed Jun 06 17:23:54 CST 2018
     */
    @SelectProvider(type=VSysUserRoleDomainSqlProvider.class, method="countByExample")
    int countByExample(VSysUserRoleDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_user_role_domain
     *
     * @mbggenerated Wed Jun 06 17:23:54 CST 2018
     */
    @SelectProvider(type=VSysUserRoleDomainSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain_id", property="domainId", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain_name", property="domainName", jdbcType=JdbcType.VARCHAR)
    })
    List<VSysUserRoleDomain> selectByExample(VSysUserRoleDomainExample example);
}